### ISSUE TITLE
CycloneDX version 1.6

### ISSUE THREAD

**Issue by m4nch0t** [productaize/bogrod#32]
Hello!
I want to evaluate your product, seems nice and love the mindset!
Unfortunately syft/grype/trivy move to cyclonedx 1.6 (we can't force 1.5 with trivy and grype) and bogrod doesn't handle it. Not really a python ninja and you got a todo in controller.py for the schema so don't really know if a PR could be accurate. Without taking in account your refactoring issue running :)

**Comment by productaize** [comment]
Thank you for your feedback - good catch! I have fixed it on master and will publish a new release shortly.

**Comment by productaize** [comment]
> I want to evaluate your product, seems nice and love the mindset!

Thanks for the feedback, glad if it helps. Feel free to reach out on github or [X](https://x.com/productaizery), happy to get your thoughts 🙏
